### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by TemporarilyOffline** [n7tae/mvoice#19]
During our live stream playing with the software:  https://youtube.com/live/okioT5H_jN8 (we didn't know what we were doing going in, that's the show's premise) we uncovered an issue (and forgive me because this was while live streaming which is hectic).

Step 1: Attempt connection to a known down module (M17-621) - failure
Step 2: Attempt to connect to a known working module (M17-M17)  - failure
Step 3: (possibly) restart mvoice and connect to a working module (M17-M17) - failure
Step 4: reboot raspberry pi, connect to a working module (M17-M17) - success

The M17-621 module had a bad IP address in the upstream database, mvoice couldn't recover.

Just a weird edge case that I wanted to make you aware of.

**Comment by n7tae** [comment]
This was excruciatingly painful to watch, but I guess the good thing is that you did find a bug. I think I know what this is about and am working on it.

In the mean time, there is a new version because the default bootstrap address needs to change, USA is no longer on openquad.net. Also, for Debian 12 and Ubuntu 24, the OpenDHT library, libopendht-dev is available instead of building your own.

**Comment by n7tae** [comment]
This should be fixed now. This should also fix the note.get() unsuccessful error as well.
